[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["."]

[project]
name = "steering_38c3"
version = "0.1.0"
dependencies = [
    "transformers",
    "nnsight==0.4.0.dev",
]